 #APPLICATION-PROPERTIES
server:
  address: localhost
  port: 7070
  context-path: /crud
  
#DBCONNECTION-PROPERTIES
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edx_db?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy:  org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
 